<%setopt("strip", False)%>
#%RAML 1.0
title: 嘿店开放平台 API
version: v1
baseUri: http://api.heidianer.com


types:
  %for serializer in serializers:
  {{ serializer.id }}:
    type: object
    properties:
      %for field in serializer.fields:
      {{ field.name }}:
        required: {{ field.required_json }}
        type: {{ field.type }}
      %endfor

  %endfor


%for api in apis:

{{ api.path }}:
  %for operation in api.operations:
  {{ operation.method }}:
    %if operation.query_parameters:
    queryParameters:
    %for parameter in operation.query_parameters:
      {{ parameter.name }}:
        required: {{ parameter.required_json }}
        %if parameter.type == 'enum':
        enum:
          %for item in parameter.enum:
          - {{ item }}
          %endfor
        %else:
        type: {{ parameter.type }}
        %endif
    %endfor

    %endif
    %if operation.method in ['post', 'put', 'patch'] and operation.serializer_name:
    body:
      application/json:
        schema: Write{{ operation.serializer_name }}

    %endif
    responses:
      200:
        body:
          application/json:
            schema: {{ operation.serializer_name }}

  %endfor

%endfor
