<%setopt("strip", False)%>
#%RAML 1.0
title: {{ title }}
baseUri: {{ base_uri }}

%if serializers:
types:
  %for serializer in serializers:
  {{ serializer.id }}:
    type: object
    properties:
      %for field in serializer.fields:
      {{ field.name }}:
        required: {{ field.required_json }}
        type: {{ field.type }}
      %endfor

  %endfor
%endif


%for api in apis:
{{ api.path }}:
  %for operation in api.operations:
  {{ operation.method }}:
    %if operation.patch:
    {{ operation.patch.content.strip() }}
    %else:
    %if operation.query_parameters:
    queryParameters:
    %for parameter in operation.query_parameters:
      {{ parameter.name }}:
        required: {{ parameter.required_json }}
        %if parameter.type == 'enum':
        enum:
          %for item in parameter.enum:
          - {{ item }}
          %endfor
        %else:
        type: {{ parameter.type }}
        %endif
    %endfor

    %endif
    %if operation.method in ['post', 'put', 'patch'] and operation.serializer_name:
    body:
      application/json:
        type: {{ operation.serializer_name_write }}

    %endif
    responses:
      200:
        %if operation.method not in ['delete']:
        body:
          application/json:
            type: {{ operation.serializer_name }}
        %endif
    %endif

  %endfor

%endfor

%for api_path in sorted(expands):
{{ api_path }}:
  %for patch in expands[api_path]:
  {{ patch.method }}:
    {{ patch.content.strip() }}

  %endfor

%endfor

