<%setopt("strip", False)%>
#%RAML 1.0
title: 嘿店开放平台 API
version: v1
baseUri: http://api.heidianer.com


types:
  %for serializer in serializers:
  {{ serializer.id }}:
    type: object
    properties:
      %for field in serializer.fields:
      {{ field.name }}: {{ field.type }}
      %endfor

  %endfor


%for api in apis:

{{ api.path }}:
  %for operation in api.operations:
  {{ operation.method }}:
    %if (operation.path_parameters):
    uriParameters:
    %for parameter in operation.path_parameters:
      {{ parameter.name }}:
        type: {{ parameter.type }}
        required: {{ parameter.required_json }}
    %endfor

    %endif
    %if (operation.query_parameters):
    queryParameters:
    %for parameter in operation.query_parameters:
      {{ parameter.name }}:
        type: {{ parameter.type }}
        required: {{ parameter.required_json }}
    %endfor

    %endif
    responses:
      200:
        body:
          application/json:
            example: |
              {}

  %endfor

%endfor
